name: NPM Packages Test & Build

on:
  workflow_call:
    inputs:
      changed_packages:
        description: "JSON array of changed packages"
        required: true
        type: string
    secrets:
      ORG_REPO_TOKEN:
        required: true

jobs:
  test-build:
    name: Test & Build (${{ matrix.package }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(inputs.changed_packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ORG_REPO_TOKEN }}

      - name: Setup Node & Yarn
        uses: Volontariapp/ci-tools/.github/actions/setup-node-yarn@main
        with:
          node-version: 24.14.0
          cache: "yarn"

      - name: Install Dependencies
        run: cd packages/${{ matrix.package }} && yarn workspaces focus


      - name: Build Package
        run: |
          PKG_NAME=$(node -p "require('./packages/${{ matrix.package }}/package.json').name")
          yarn workspaces foreach -Rt --from "$PKG_NAME" run build

      - name: Build Test Database
        if: ${{ matrix.package == 'database' || matrix.package == 'bridge' || matrix.package == 'bridge-nest' || matrix.package == 'health-check' || matrix.package == 'health-check-nest' }}
        run: docker compose -f ci-tools/testing/docker-compose.yml --profile test build

      - name: Setup Test Database
        if: ${{ matrix.package == 'database' || matrix.package == 'bridge' || matrix.package == 'bridge-nest' || matrix.package == 'health-check' || matrix.package == 'health-check-nest' }}
        run: docker compose -f ci-tools/testing/docker-compose.yml --profile test up -d --wait

      - name: Test Package
        run: cd packages/${{ matrix.package }} && yarn test
