name: Global Sync CI-Tools

on:
  push:
    branches:
      - main

jobs:
  sync-repositories:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git Configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global url."https://x-access-token:${{ secrets.ORG_REPO_TOKEN }}@github.com/".insteadOf "git@github.com:"

      - name: Update each Service and Push
        env:
          ORG_REPO_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
        run: |
          if [ -z "$ORG_REPO_TOKEN" ]; then
            echo "ORG_REPO_TOKEN is empty or not available in this workflow run."
            exit 1
          fi

          SERVICES=("api-gateway" "ms-event" "ms-post" "ms-user" "nativapp" "npm-packages" "changelog-checker" "proto-registry")

          for repo in "${SERVICES[@]}"; do
            echo "Processing $repo..."

            git clone --recursive https://x-access-token:$ORG_REPO_TOKEN@github.com/Volontariapp/$repo.git $repo
            cd $repo

            git submodule update --remote ci-tools

            if ! git diff --quiet; then
              git add ci-tools
              git commit -m "chore: update ci-tools to latest version"
              git remote set-url origin "https://x-access-token:${ORG_REPO_TOKEN}@github.com/Volontariapp/${repo}.git"
              git push origin main
            else
              echo "No changes for $repo"
            fi

            cd ..
            rm -rf $repo
          done
