name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ci:
    uses: Volontariapp/ci-tools/.github/workflows/ci-service.yml@main
    with:
      service-name: ms-social
    secrets: inherit

  smoke-test:
    needs: ci
    uses: Volontariapp/ci-tools/.github/workflows/ci-docker-smoke.yml@main
    with:
      service-name: ms-social
      db-name: "ms_social"
      db-user: "user"
      db-password: "password"
      db-type: "postgres-neo4j"
      port: 3004
    secrets: inherit
