name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  ci:
    uses: Volontariapp/ci-tools/.github/workflows/services/ci.yml@main
    with:
      service-name: ms-social
    secrets: inherit

  smoke-test:
    needs: ci
    uses: Volontariapp/ci-tools/.github/workflows/services/docker-smoke.yml@main
    with:
      service-name: ms-social
      db-name: "ms_social"
      db-user: "user"
      db-password: "password"
      db-type: "postgres-neo4j"
      port: 3004
    secrets: inherit

  ci-docker:
    needs: ci
    permissions:
      contents: read
      packages: write
    uses: Volontariapp/ci-tools/.github/workflows/services/docker-build-push.yml@main
    with:
      service-name: ms-social
    secrets: inherit

  e2e:
    needs: [ci-docker, smoke-test]
    uses: Volontariapp/ci-tools/.github/workflows/e2e/orchestrator.yml@main
    secrets: inherit

  validate-e2e-matrix:
    uses: Volontariapp/ci-tools/.github/workflows/e2e/matrix-checker.yml@main
    with:
      service-name: ms-social
